import { Wizard2026CatalogItem } from './wizard2026LetterTypes';
import { getDl25ApplicabilityStatus } from '../../../logic/wizard2026';

export const wizard2026LetterCatalog: Wizard2026CatalogItem[] = [
  // ── STEP 1: ENTE E CONDIZIONI PRELIMINARI ─────────────────────────────────
  {
    stepId: 1,
    stepTitle: 'Dati generali dell’Ente',
    field: 'ente.denominazioneEnte',
    label: 'Denominazione Ente',
    descrizione: 'Denominazione dell\'Ente attivo selezionato.',
    norma: 'Inquadramento generale',
    percheServe: 'serve per l\'intestazione formale della lettera e per associare correttamente l\'istruttoria.',
    obbligatorieta: 'OBBLIGATORIO',
    destinatarioSuggerito: 'Ufficio Personale'
  },
  {
    stepId: 1,
    stepTitle: 'Dati generali dell’Ente',
    field: 'ente.annoRiferimento',
    label: 'Anno di Riferimento Istruttoria',
    descrizione: 'Anno per cui si compila il wizard.',
    norma: 'Inquadramento generale',
    percheServe: 'serve per identificare l\'annualità contabile di riferimento per l\'applicazione delle regole normative vigenti.',
    obbligatorieta: 'OBBLIGATORIO',
    destinatarioSuggerito: 'Ufficio Personale'
  },
  {
    stepId: 1,
    stepTitle: 'Dati generali dell’Ente',
    field: 'ente.entityType',
    label: 'Qualificazione Giuridica (Tipologia Ente)',
    descrizione: 'Seleziona una tipologia dall\'elenco (Comune, Provincia, Unione, ecc.).',
    norma: 'Inquadramento generale',
    percheServe: 'serve per determinare la tipologia di ente e applicare i relativi vincoli e parametri di spesa (ad es. D.L. 25/2025).',
    obbligatorieta: 'OBBLIGATORIO',
    destinatarioSuggerito: 'Ufficio Personale'
  },
  {
    stepId: 1,
    stepTitle: 'Dati generali dell’Ente',
    field: 'ente.hasDirigenza',
    label: 'Presenza della Dirigenza',
    descrizione: 'Indicare se l\'ente ha o meno personale dirigente in organico (Sì/No).',
    norma: 'Art. 23, comma 2, D.Lgs. 75/2017',
    percheServe: 'serve per stabilire l\'eventuale computo del limite accessorio per l\'area dirigenziale.',
    obbligatorieta: 'OBBLIGATORIO',
    destinatarioSuggerito: 'Ufficio Personale'
  },
  {
    stepId: 1,
    stepTitle: 'Dati generali dell’Ente',
    field: 'ente.isDissesto',
    label: 'Ente in Stato di Dissesto Finanziario',
    descrizione: 'Indicare se l\'ente si trova in stato di dissesto finanziario (Sì/No).',
    norma: 'Art. 244, D.Lgs. 267/2000 (TUEL)',
    percheServe: 'serve per verificare l\'applicabilità di limitazioni ed esclusioni collegate a situazioni di criticità finanziaria.',
    obbligatorieta: 'OBBLIGATORIO',
    destinatarioSuggerito: 'Ufficio Ragioneria'
  },
  {
    stepId: 1,
    stepTitle: 'Dati generali dell’Ente',
    field: 'ente.isStrutturalmenteDeficitario',
    label: 'Ente in Condizioni di Deficitarietà Strutturale',
    descrizione: 'Indicare se l\'ente è strutturalmente deficitario (Sì/No).',
    norma: 'Art. 242, D.Lgs. 267/2000 (TUEL)',
    percheServe: 'serve per rilevare la sussistenza dei controlli previsti per gli enti strutturalmente deficitari.',
    obbligatorieta: 'OBBLIGATORIO',
    destinatarioSuggerito: 'Ufficio Ragioneria'
  },
  {
    stepId: 1,
    stepTitle: 'Dati generali dell’Ente',
    field: 'ente.isPianoRiequilibrio',
    label: 'Ente in Piano di Riequilibrio Finanziario Pluriennale',
    descrizione: 'Indicare se l\'ente ha un piano di riequilibrio deliberato (Sì/No).',
    norma: 'Art. 243-bis, D.Lgs. 267/2000 (TUEL)',
    percheServe: 'serve per valutare la coerenza con i vincoli e gli obiettivi fissati nel piano deliberato.',
    obbligatorieta: 'OBBLIGATORIO',
    destinatarioSuggerito: 'Ufficio Ragioneria'
  },
  {
    stepId: 1,
    stepTitle: 'Dati generali dell’Ente',
    field: 'ente.isPrimaFasciaDl34',
    label: 'Comune in Prima Fascia di Virtuosità D.L. 34/2019',
    descrizione: 'Solo per i Comuni. Indica se il Comune appartiene alla fascia di massima virtuosità assunzioni (Sì/No).',
    norma: 'Art. 33, D.L. 34/2019',
    percheServe: 'serve per determinare la capienza e la sostenibilità finanziaria delle spese di personale.',
    obbligatorieta: 'CONDIZIONALE',
    destinatarioSuggerito: 'Ufficio Ragioneria',
    includeWhen: (s) => s.ente.entityType === 'COMUNE'
  },
  {
    stepId: 1,
    stepTitle: 'Dati generali dell’Ente',
    field: 'ente.isEquilibrioPluriennaleAsseverato',
    label: 'Equilibrio di Bilancio Pluriennale Asseverato',
    descrizione: 'Indicare se gli equilibri di bilancio pluriennali sono regolarmente asseverati (Sì/No).',
    norma: 'Regole contabili generali',
    percheServe: 'serve per verificare il presupposto essenziale di compatibilità e sostenibilità economico-finanziaria.',
    obbligatorieta: 'OBBLIGATORIO',
    destinatarioSuggerito: 'Ufficio Ragioneria'
  },
  {
    stepId: 1,
    stepTitle: 'Dati generali dell’Ente',
    field: 'ente.hasApprovazioneCosfel',
    label: 'Approvazione COSFEL ottenuta per le assunzioni/spesa',
    descrizione: 'Se l\'ente ha criticità finanziarie (dissesto/deficitario/riequilibrio), indicare se è stata ottenuta l\'approvazione COSFEL (Sì/No).',
    norma: 'Art. 243, D.Lgs. 267/2000',
    percheServe: 'serve per attestare il possesso dell\'autorizzazione ministeriale necessaria per deliberare spese di personale per gli enti in pre-dissesto o dissesto.',
    obbligatorieta: 'CONDIZIONALE',
    destinatarioSuggerito: 'Ufficio Ragioneria',
    includeWhen: (s) => !!(s.ente.isDissesto || s.ente.isStrutturalmenteDeficitario || s.ente.isPianoRiequilibrio)
  },

  // ── STEP 2: ARTICOLO 23 ───────────────────────────────────────────────────
  {
    stepId: 2,
    stepTitle: 'Limite art. 23',
    field: 'art23.limite2016CertificatoEnte',
    label: 'Limite Complessivo Trattamento Accessorio 2016 Certificato',
    descrizione: 'Il tetto storico complessivo del trattamento accessorio per l\'anno 2016 (certificato dai revisori).',
    norma: 'Art. 23, comma 2, D.Lgs. 75/2017',
    percheServe: 'serve per disporre del limite massimo complessivo di spesa accessoria certificato dai revisori.',
    obbligatorieta: 'OBBLIGATORIO',
    destinatarioSuggerito: 'Ufficio Ragioneria'
  },
  {
    stepId: 2,
    stepTitle: 'Limite art. 23',
    field: 'art23.fondoPersonaleDipendente2016',
    label: 'di cui: Fondo risorse decentrate personale dipendente 2016',
    descrizione: 'Quota parte del tetto 2016 destinata al personale non dirigente.',
    norma: 'Art. 23, comma 2, D.Lgs. 75/2017',
    percheServe: 'serve per identificare la porzione storica del tetto 2016 destinata specificamente al personale del comparto.',
    obbligatorieta: 'OBBLIGATORIO',
    destinatarioSuggerito: 'Ufficio Personale'
  },
  {
    stepId: 2,
    stepTitle: 'Limite art. 23',
    field: 'art23.fondoEqPo2016',
    label: 'di cui: Risorse destinate alle Elevate Qualificazioni (ex P.O.) 2016',
    descrizione: 'Quota parte del tetto 2016 destinata alle Posizioni Organizzative / Elevate Qualificazioni.',
    norma: 'Art. 23, comma 2, D.Lgs. 75/2017',
    percheServe: 'serve per isolare la quota del tetto storico 2016 dedicata alle posizioni organizzative ed elevate qualificazioni.',
    obbligatorieta: 'OBBLIGATORIO',
    destinatarioSuggerito: 'Ufficio Personale'
  },
  {
    stepId: 2,
    stepTitle: 'Limite art. 23',
    field: 'art23.fondoDirigenza2016',
    label: 'di cui: Fondo personale dirigente 2016',
    descrizione: 'Quota parte del tetto 2016 destinata ai dirigenti (se presente la dirigenza).',
    norma: 'Art. 23, comma 2, D.Lgs. 75/2017',
    percheServe: 'serve per verificare il tetto storico accessorio per la dirigenza, qualora l\'ente sia provvisto di tale qualifica.',
    obbligatorieta: 'CONDIZIONALE',
    destinatarioSuggerito: 'Ufficio Personale',
    includeWhen: (s) => !!s.ente.hasDirigenza
  },
  {
    stepId: 2,
    stepTitle: 'Limite art. 23',
    field: 'art23.risorseSegretario2016',
    label: 'di cui: Risorse segretario comunale/provinciale 2016',
    descrizione: 'Quota parte del tetto 2016 per la retribuzione di posizione e risultato del segretario comunale.',
    norma: 'Art. 23, comma 2, D.Lgs. 75/2017',
    percheServe: 'serve per scorporare la spesa accessoria sostenuta nel 2016 per la figura del segretario.',
    obbligatorieta: 'OPZIONALE',
    destinatarioSuggerito: 'Ufficio Personale'
  },
  {
    stepId: 2,
    stepTitle: 'Limite art. 23',
    field: 'art23.altreVoci2016Soggette',
    label: 'di cui: Altre voci accessorie soggette al limite 2016',
    descrizione: 'Eventuali altre voci accessorie erogate fuori dai fondi ma soggette al limite nel 2016.',
    norma: 'Art. 23, comma 2, D.Lgs. 75/2017',
    percheServe: 'serve per quantificare ulteriori voci accessorie corrisposte al di fuori dei fondi stabili nell\'anno 2016.',
    obbligatorieta: 'OPZIONALE',
    destinatarioSuggerito: 'Ufficio Personale'
  },
  {
    stepId: 2,
    stepTitle: 'Limite art. 23',
    field: 'art23.fondoDipendenti2018Soggetto',
    label: 'Fondo dipendenti 2018 soggetto al limite (valore storico)',
    descrizione: 'Necessario per il calcolo dell\'adeguamento del valore medio pro capite (Art. 33 D.L. 34/2019).',
    norma: 'Art. 33, D.L. 34/2019',
    percheServe: 'serve per stabilire il parametro di base del Fondo 2018 per l\'adeguamento proporzionale alle variazioni di personale.',
    obbligatorieta: 'OBBLIGATORIO',
    destinatarioSuggerito: 'Ufficio Personale'
  },
  {
    stepId: 2,
    stepTitle: 'Limite art. 23',
    field: 'art23.risorsePoEq2018Soggette',
    label: 'Risorse P.O./E.Q. 2018 soggette al limite (valore storico)',
    descrizione: 'Valore delle risorse per posizioni organizzative destinate nel 2018.',
    norma: 'Art. 33, D.L. 34/2019',
    percheServe: 'serve per disporre della spesa per EQ del 2018 utile al calcolo del valore medio accessorio pro capite.',
    obbligatorieta: 'OBBLIGATORIO',
    destinatarioSuggerito: 'Ufficio Personale'
  },
  {
    stepId: 2,
    stepTitle: 'Limite art. 23',
    field: 'art23.personaleServizio31122018',
    label: 'Personale in servizio al 31/12/2018 (valore medio pro capite)',
    descrizione: 'Consistenza di personale in servizio a fine 2018 utilizzata come base pro-capite.',
    norma: 'Art. 33, D.L. 34/2019',
    percheServe: 'serve come consistenza organica di riferimento (denominatore) del 2018 per il calcolo del limite pro capite.',
    obbligatorieta: 'OBBLIGATORIO',
    destinatarioSuggerito: 'Ufficio Personale'
  },
  {
    stepId: 2,
    stepTitle: 'Limite art. 23',
    field: 'art23.personalePrevisto2026Piao',
    label: 'Personale previsto nell\'anno di riferimento (PIAO)',
    descrizione: 'Consistenza programmata nel PIAO per l\'anno di riferimento.',
    norma: 'Art. 33, D.L. 34/2019',
    percheServe: 'serve come consistenza programmata per l\'anno di istruttoria (numeratore) per calcolare la variazione del limite.',
    obbligatorieta: 'OBBLIGATORIO',
    destinatarioSuggerito: 'Ufficio Personale'
  },
  {
    stepId: 2,
    stepTitle: 'Limite art. 23',
    field: 'art23.usaCalcoloManualePersonaleArt23',
    label: 'Usa inserimento manuale dipendenti equivalenti per Art. 23',
    descrizione: 'Consente di inserire direttamente i dipendenti equivalenti per il ricalcolo del limite (Sì/No).',
    norma: 'Inquadramento generale',
    percheServe: 'serve per abilitare l\'inserimento aggregato dei dipendenti equivalenti in deroga al calcolo analitico basato sul PIAO.',
    obbligatorieta: 'OBBLIGATORIO',
    destinatarioSuggerito: 'Ufficio Personale'
  },
  {
    stepId: 2,
    stepTitle: 'Limite art. 23',
    field: 'art23.manualDipendentiEquivalenti2018',
    label: 'Valore manuale dipendenti equivalenti 2018',
    descrizione: 'Valore manuale dipendenti equivalenti per il 2018.',
    norma: 'Art. 33, D.L. 34/2019',
    percheServe: 'serve per specificare il dato sui dipendenti 2018 se è attiva la modalità manuale.',
    obbligatorieta: 'CONDIZIONALE',
    destinatarioSuggerito: 'Ufficio Personale',
    includeWhen: (s) => !!s.art23.usaCalcoloManualePersonaleArt23
  },
  {
    stepId: 2,
    stepTitle: 'Limite art. 23',
    field: 'art23.manualDipendentiEquivalenti2026',
    label: 'Valore manuale dipendenti equivalenti anno riferimento',
    descrizione: 'Valore manuale dipendenti equivalenti per l\'anno corrente.',
    norma: 'Art. 33, D.L. 34/2019',
    percheServe: 'serve per indicare la consistenza organica programmata dell\'anno di riferimento in modalità manuale.',
    obbligatorieta: 'CONDIZIONALE',
    destinatarioSuggerito: 'Ufficio Personale',
    includeWhen: (s) => !!s.art23.usaCalcoloManualePersonaleArt23
  },
  {
    stepId: 2,
    stepTitle: 'Limite art. 23',
    field: 'art23.personaleTempoIndeterminato2026',
    label: 'Personale a tempo indeterminato anno riferimento',
    descrizione: 'Organico a tempo indeterminato programmato.',
    norma: 'Art. 33, D.L. 34/2019',
    percheServe: 'serve per quantificare analiticamente la consistenza di personale di ruolo prevista nell\'anno.',
    obbligatorieta: 'CONDIZIONALE',
    destinatarioSuggerito: 'Ufficio Personale',
    includeWhen: (s) => !s.art23.usaCalcoloManualePersonaleArt23
  },
  {
    stepId: 2,
    stepTitle: 'Limite art. 23',
    field: 'art23.personaleTempoDeterminato2026',
    label: 'Personale a tempo determinato anno riferimento',
    descrizione: 'Organico a tempo determinato programmato.',
    norma: 'Art. 33, D.L. 34/2019',
    percheServe: 'serve per inserire nel conteggio dei dipendenti equivalenti la quota programmata per i contratti a termine.',
    obbligatorieta: 'CONDIZIONALE',
    destinatarioSuggerito: 'Ufficio Personale',
    includeWhen: (s) => !s.art23.usaCalcoloManualePersonaleArt23
  },
  {
    stepId: 2,
    stepTitle: 'Limite art. 23',
    field: 'art23.assunzioniPreviste2026',
    label: 'Assunzioni previste anno riferimento',
    descrizione: 'Totale assunzioni programmate nell\'anno.',
    norma: 'Art. 33, D.L. 34/2019',
    percheServe: 'serve per stimare l\'adeguamento in aumento del personale previsto per i mesi lavorativi dell\'anno.',
    obbligatorieta: 'CONDIZIONALE',
    destinatarioSuggerito: 'Ufficio Personale',
    includeWhen: (s) => !s.art23.usaCalcoloManualePersonaleArt23
  },
  {
    stepId: 2,
    stepTitle: 'Limite art. 23',
    field: 'art23.cessazioniPreviste2026',
    label: 'Cessazioni previste anno riferimento',
    descrizione: 'Totale cessazioni programmate nell\'anno.',
    norma: 'Art. 33, D.L. 34/2019',
    percheServe: 'serve per detrarre dal personale previsto le cessazioni calendarizzate nel corso dell\'anno.',
    obbligatorieta: 'CONDIZIONALE',
    destinatarioSuggerito: 'Ufficio Personale',
    includeWhen: (s) => !s.art23.usaCalcoloManualePersonaleArt23
  },

  // ── STEP 3: D.L. 25/2025 (LIMITI E SOSTENIBILITA') ────────────────────────
  {
    stepId: 3,
    stepTitle: 'Limite massimo D.L. 25',
    field: 'dl25.stipendiTabellari2023NonDirigenti',
    label: 'Spesa per stipendi tabellari 2023 del personale non dirigente',
    descrizione: 'Spesa sostenuta nel 2023 per gli stipendi tabellari del personale non dirigente (esclusi oneri e IRAP).',
    norma: 'Articolo unico, D.L. 25/2025',
    percheServe: 'serve per determinare il valore soglia del 48% su cui calcolare l\'incremento massimo teorico del fondo.',
    obbligatorieta: 'CONDIZIONALE',
    destinatarioSuggerito: 'Ufficio Ragioneria',
    includeWhen: (s) => !!s.ente.entityType && getDl25ApplicabilityStatus(s.ente.entityType) === 'DIRECTLY_APPLICABLE'
  },
  {
    stepId: 3,
    stepTitle: 'Limite massimo D.L. 25',
    field: 'dl25.fondoStabile2025Certificato',
    label: 'Consistenza Fondo risorse decentrate parte stabile dell’anno precedente',
    descrizione: 'La consistenza della sola parte stabile del Fondo risorse decentrate dell\'anno precedente certificata dai revisori.',
    norma: 'Articolo unico, D.L. 25/2025',
    percheServe: 'serve per sottrarre la parte stabile già consolidata dal limite teorico del 48%, individuando lo spazio di incremento residuo.',
    obbligatorieta: 'CONDIZIONALE',
    destinatarioSuggerito: 'Ufficio Personale',
    includeWhen: (s) => !!s.ente.entityType && getDl25ApplicabilityStatus(s.ente.entityType) === 'DIRECTLY_APPLICABLE'
  },
  {
    stepId: 3,
    stepTitle: 'Limite massimo D.L. 25',
    field: 'dl25.budgetEq2025',
    label: 'Budget Elevate Qualificazioni dell’anno precedente',
    descrizione: 'Risorse complessivamente destinate alle Elevate Qualificazioni dell\'anno precedente certificate.',
    norma: 'Articolo unico, D.L. 25/2025',
    percheServe: 'serve per sommare le risorse per le EQ a quelle del Fondo ed eseguire la decurtazione dalla soglia del 48%.',
    obbligatorieta: 'CONDIZIONALE',
    destinatarioSuggerito: 'Ufficio Personale',
    includeWhen: (s) => !!s.ente.entityType && getDl25ApplicabilityStatus(s.ente.entityType) === 'DIRECTLY_APPLICABLE'
  },
  {
    stepId: 3,
    stepTitle: 'Limite massimo D.L. 25',
    field: 'dl25.altreRisorse2025DaSottrarre',
    label: 'Altre risorse dell\'anno precedente da sottrarre',
    descrizione: 'Altre risorse stabili erogate nell\'anno precedente esterne al Fondo che vanno sottratte in base alle circolari applicative.',
    norma: 'Articolo unico, D.L. 25/2025',
    percheServe: 'serve per depurare il limite da componenti accessorie esterne già consolidate onde evitare duplicazioni di spesa.',
    obbligatorieta: 'OPZIONALE',
    destinatarioSuggerito: 'Ufficio Ragioneria',
    includeWhen: (s) => !!s.ente.entityType && getDl25ApplicabilityStatus(s.ente.entityType) === 'DIRECTLY_APPLICABLE'
  },
  {
    stepId: 3,
    stepTitle: 'Limite massimo D.L. 25',
    field: 'dl25.popolazioneEnte',
    label: 'Popolazione residente (per Comuni)',
    descrizione: 'Popolazione residente al 31/12 dell\'anno precedente.',
    norma: 'D.M. 17 marzo 2020',
    percheServe: 'serve per individuare i parametri corretti e le fasce demografiche del Comune per la verifica di virtuosità.',
    obbligatorieta: 'CONDIZIONALE',
    destinatarioSuggerito: 'Ufficio Ragioneria',
    includeWhen: (s) => s.ente.entityType === 'COMUNE'
  },
  {
    stepId: 3,
    stepTitle: 'Limite massimo D.L. 25',
    field: 'dl25.entrateCorrentiN1',
    label: 'Entrate correnti (Rendiconto anno N-1)',
    descrizione: 'Entrate correnti per il calcolo degli indici di virtuosità (Rendiconto anno precedente).',
    norma: 'D.M. 17 marzo 2020',
    percheServe: 'serve per disporre delle entrate correnti dell\'anno precedente utili al calcolo della media triennale.',
    obbligatorieta: 'CONDIZIONALE',
    destinatarioSuggerito: 'Ufficio Ragioneria',
    includeWhen: (s) => s.ente.entityType === 'COMUNE'
  },
  {
    stepId: 3,
    stepTitle: 'Limite massimo D.L. 25',
    field: 'dl25.entrateCorrentiN2',
    label: 'Entrate correnti (Rendiconto anno N-2)',
    descrizione: 'Entrate correnti (Rendiconto due anni precedenti).',
    norma: 'D.M. 17 marzo 2020',
    percheServe: 'serve per completare il triennio di bilancio necessario alla media delle entrate correnti.',
    obbligatorieta: 'CONDIZIONALE',
    destinatarioSuggerito: 'Ufficio Ragioneria',
    includeWhen: (s) => s.ente.entityType === 'COMUNE'
  },
  {
    stepId: 3,
    stepTitle: 'Limite massimo D.L. 25',
    field: 'dl25.entrateCorrentiN3',
    label: 'Entrate correnti (Rendiconto anno N-3)',
    descrizione: 'Entrate correnti (Rendiconto tre anni precedenti).',
    norma: 'D.M. 17 marzo 2020',
    percheServe: 'serve per integrare il terzo anno utile al calcolo della media delle entrate correnti.',
    obbligatorieta: 'CONDIZIONALE',
    destinatarioSuggerito: 'Ufficio Ragioneria',
    includeWhen: (s) => s.ente.entityType === 'COMUNE'
  },
  {
    stepId: 3,
    stepTitle: 'Limite massimo D.L. 25',
    field: 'dl25.fcdeStanziato',
    label: 'FCDE stanziato nel bilancio di previsione',
    descrizione: 'Fondo Crediti di Dubbia Esigibilità stanziato nel bilancio di previsione corrente.',
    norma: 'D.M. 17 marzo 2020',
    percheServe: 'serve per depurare le entrate correnti calcolando la quota netta disponibile per la spesa.',
    obbligatorieta: 'CONDIZIONALE',
    destinatarioSuggerito: 'Ufficio Ragioneria',
    includeWhen: (s) => s.ente.entityType === 'COMUNE'
  },
  {
    stepId: 3,
    stepTitle: 'Limite massimo D.L. 25',
    field: 'dl25.spesaPersonaleUltimoRendiconto',
    label: 'Spesa del personale dell\'ultimo rendiconto approvato',
    descrizione: 'Spesa totale del personale registrata a consuntivo.',
    norma: 'D.M. 17 marzo 2020',
    percheServe: 'serve per verificare il rapporto spesa/entrate dell\'ente ed accertare la virtuosità finanziaria.',
    obbligatorieta: 'CONDIZIONALE',
    destinatarioSuggerito: 'Ufficio Ragioneria',
    includeWhen: (s) => s.ente.entityType === 'COMUNE'
  },
  {
    stepId: 3,
    stepTitle: 'Limite massimo D.L. 25',
    field: 'dl25.limiteStoricoSpesaPersonale',
    label: 'Spesa del personale di riferimento storica (limite spesa)',
    descrizione: 'Valore limite storico per la spesa del personale dell\'ente.',
    norma: 'Limiti generali di spesa',
    percheServe: 'serve come tetto di controllo finale per garantire la sostenibilità globale della spesa di personale.',
    obbligatorieta: 'CONDIZIONALE',
    destinatarioSuggerito: 'Ufficio Ragioneria',
    includeWhen: (s) => !!s.ente.entityType && getDl25ApplicabilityStatus(s.ente.entityType) === 'DIRECTLY_APPLICABLE'
  },
  {
    stepId: 3,
    stepTitle: 'Limite massimo D.L. 25',
    field: 'dl25.baseCalcoloLimiteStorico',
    label: 'Base di calcolo limite storico',
    descrizione: 'Indicazione della norma o della base storica del limite di spesa del personale.',
    norma: 'Limiti di spesa',
    percheServe: 'serve per specificare quale parametro normativo storico o di bilancio l\'ente adotta per il suo tetto di spesa.',
    obbligatorieta: 'CONDIZIONALE',
    destinatarioSuggerito: 'Ufficio Ragioneria',
    includeWhen: (s) => !!s.ente.entityType && getDl25ApplicabilityStatus(s.ente.entityType) === 'DIRECTLY_APPLICABLE'
  },
  {
    stepId: 3,
    stepTitle: 'Limite massimo D.L. 25',
    field: 'dl25.spesaPersonalePrevista2026AnteIncremento',
    label: 'Spesa personale prevista anno riferimento (ante incremento)',
    descrizione: 'Spesa complessiva prevista per il personale nell\'anno prima dell\'applicazione del D.L. 25.',
    norma: 'Verifica limite spesa',
    percheServe: 'serve per quantificare il margine di capienza del bilancio prima di inserire il nuovo incremento accessorio.',
    obbligatorieta: 'CONDIZIONALE',
    destinatarioSuggerito: 'Ufficio Ragioneria',
    includeWhen: (s) => !!s.ente.entityType && getDl25ApplicabilityStatus(s.ente.entityType) === 'DIRECTLY_APPLICABLE'
  },
  {
    stepId: 3,
    stepTitle: 'Limite massimo D.L. 25',
    field: 'dl25.documentazioneCosfelDl25',
    label: 'Estremi autorizzazione COSFEL per D.L. 25',
    descrizione: 'Indicare la delibera COSFEL autorizzativa se applicabile.',
    norma: 'COSFEL / D.L. 25/2025',
    percheServe: 'serve per verificare l\'avvenuta autorizzazione all\'adeguamento del fondo per gli enti in pre-dissesto o dissesto.',
    obbligatorieta: 'CONDIZIONALE',
    destinatarioSuggerito: 'Ufficio Ragioneria',
    includeWhen: (s) => s.ente.isStrutturalmenteDeficitario === true && !!s.ente.entityType && getDl25ApplicabilityStatus(s.ente.entityType) === 'DIRECTLY_APPLICABLE'
  },
  
  // Campi per UNIONE_COMUNI / TRANSFER_ONLY
  {
    stepId: 3,
    stepTitle: 'Limite massimo D.L. 25',
    field: 'dl25.quotaTrasferitaAderentiDL25_2025',
    label: 'Quota massima trasferibile dagli enti aderenti',
    descrizione: 'Risorse trasferite per il finanziamento dei servizi associati o unificati dagli enti aderenti.',
    norma: 'Articolo unico, D.L. 25/2025',
    percheServe: 'serve per verificare l\'ammontare complessivo delle quote trasferite dai singoli comuni all\'Unione.',
    obbligatorieta: 'CONDIZIONALE',
    destinatarioSuggerito: 'Ufficio Ragioneria',
    includeWhen: (s) => !!s.ente.entityType && getDl25ApplicabilityStatus(s.ente.entityType) === 'TRANSFER_ONLY'
  },
  {
    stepId: 3,
    stepTitle: 'Limite massimo D.L. 25',
    field: 'dl25.attiComuniAderentiPresenti',
    label: 'Presenza degli atti di tutti i comuni aderenti',
    descrizione: 'Solo per Unioni. Indica se tutti i comuni aderenti hanno deliberato il trasferimento (Sì/No).',
    norma: 'D.L. 25/2025',
    percheServe: 'serve per asseverare che ciascun comune facente parte dell\'Unione abbia formalizzato il trasferimento.',
    obbligatorieta: 'CONDIZIONALE',
    destinatarioSuggerito: 'Ufficio Ragioneria',
    includeWhen: (s) => !!s.ente.entityType && getDl25ApplicabilityStatus(s.ente.entityType) === 'TRANSFER_ONLY'
  },
  {
    stepId: 3,
    stepTitle: 'Limite massimo D.L. 25',
    field: 'dl25.riduzionePermanenteFondiComuniCertificata',
    label: 'Certificazione riduzione permanente fondi dei singoli comuni',
    descrizione: 'Solo per Unioni. Indica se i revisori hanno certificato la correlata riduzione stabile nei singoli bilanci (Sì/No).',
    norma: 'D.L. 25/2025',
    percheServe: 'serve per accertare che vi sia stata la riduzione strutturale e permanente nei bilanci originari dei singoli comuni.',
    obbligatorieta: 'CONDIZIONALE',
    destinatarioSuggerito: 'Ufficio Ragioneria',
    includeWhen: (s) => !!s.ente.entityType && getDl25ApplicabilityStatus(s.ente.entityType) === 'TRANSFER_ONLY'
  },
  {
    stepId: 3,
    stepTitle: 'Limite massimo D.L. 25',
    field: 'dl25.certificazioneRevisoriComuni',
    label: 'Certificazione dei revisori dei singoli comuni',
    descrizione: 'Solo per Unioni. Indica il parere favorevole dei revisori degli enti aderenti (Sì/No).',
    norma: 'D.L. 25/2025',
    percheServe: 'serve come parere preventivo favorevole espresso dall\'organo di controllo contabile di ciascun comune.',
    obbligatorieta: 'CONDIZIONALE',
    destinatarioSuggerito: 'Ufficio Ragioneria',
    includeWhen: (s) => !!s.ente.entityType && getDl25ApplicabilityStatus(s.ente.entityType) === 'TRANSFER_ONLY'
  },

  // ── STEP 4: CCNL 2026 ─────────────────────────────────────────────────────
  {
    stepId: 4,
    stepTitle: 'Incrementi CCNL',
    field: 'ccnl2026.monteSalari2021',
    label: 'Monte Salari anno 2021 personale non dirigente',
    descrizione: 'Il monte salari 2021 del personale non dirigente (dichiarato in conto annuale) per il calcolo degli incrementi.',
    norma: 'Art. 58, CCNL 23.02.2026',
    percheServe: 'serve come parametro base su cui applicare gli incrementi previsti dal rinnovo contrattuale.',
    obbligatorieta: 'OBBLIGATORIO',
    destinatarioSuggerito: 'Ufficio Ragioneria'
  },
  {
    stepId: 4,
    stepTitle: 'Incrementi CCNL',
    field: 'ccnl2026.monteSalari2021Consolidato2026',
    label: 'Monte Salari 2021 consolidato',
    descrizione: 'Monte Salari 2021 consolidato (trascinato dalle istruttorie precedenti).',
    norma: 'Art. 58, CCNL 23.02.2026',
    percheServe: 'serve come valore di monte salari consolidato per le istruttorie degli anni successivi al 2026.',
    obbligatorieta: 'OPZIONALE',
    destinatarioSuggerito: 'Ufficio Ragioneria'
  },
  {
    stepId: 4,
    stepTitle: 'Incrementi CCNL',
    field: 'ccnl2026.fondoRisorseDecentrate2024',
    label: 'Intero Fondo risorse decentrate anno 2024',
    descrizione: 'Base di riparto per l\'incremento dello 0,22% destinato al Fondo risorse decentrate.',
    norma: 'Art. 58, comma 2, CCNL 23.02.2026',
    percheServe: 'serve per definire la quota di base del Fondo 2024 su cui effettuare il riparto proporzionale dell\'incremento.',
    obbligatorieta: 'OBBLIGATORIO',
    destinatarioSuggerito: 'Ufficio Personale'
  },
  {
    stepId: 4,
    stepTitle: 'Incrementi CCNL',
    field: 'ccnl2026.risorseEQ2024',
    label: 'Intere risorse destinate alle Elevate Qualificazioni anno 2024',
    descrizione: 'Base di riparto per l\'incremento dello 0,22% destinato alla retribuzione di posizione e risultato delle EQ.',
    norma: 'Art. 58, comma 2, CCNL 23.02.2026',
    percheServe: 'serve per definire la quota di base delle EQ 2024 per il calcolo proporzionale dello 0,22%.',
    obbligatorieta: 'OBBLIGATORIO',
    destinatarioSuggerito: 'Ufficio Personale'
  },
  {
    stepId: 4,
    stepTitle: 'Incrementi CCNL',
    field: 'ccnl2026.incremento022Anno',
    label: 'Quota dello 0,22% che l’ente intende applicare nell’anno',
    descrizione: 'La quota effettiva dello 0,22% che si intende stanziare (limite massimo teorico calcolato automaticamente).',
    norma: 'Art. 58, comma 2, CCNL 23.02.2026',
    percheServe: 'serve per definire in istruttoria quale quota del fondo variabile del 0,22% l\'ente intende attivare.',
    obbligatorieta: 'OPZIONALE',
    destinatarioSuggerito: 'Ufficio Personale'
  },

  // ── STEP 5: CONGLOBAMENTO ARTICOLO 60 ─────────────────────────────────────
  {
    stepId: 5,
    stepTitle: 'Conglobamento comparto art. 60',
    field: 'conglobamentoArt60.mode',
    label: 'Modalità di inserimento',
    descrizione: 'Modalità di inserimento: "guided" per calcolo basato sul personale, "manual" per inserimento manuale motivato.',
    norma: 'Art. 60, CCNL 23.02.2026',
    percheServe: 'serve per determinare il percorso metodologico (assistito o manuale) per stabilire la decurtazione del fondo.',
    obbligatorieta: 'OBBLIGATORIO',
    destinatarioSuggerito: 'Ufficio Personale',
    includeWhen: (s) => (s.ente.annoRiferimento || 2026) === 2026
  },
  // AREA OPERATORE
  {
    stepId: 5,
    stepTitle: 'Conglobamento comparto art. 60',
    field: 'conglobamentoArt60.personaleInteroArea.OPERATORE',
    label: 'Area Operatori - personale computato per intero al 1° gennaio 2026',
    descrizione: 'Dipendenti a tempo pieno, dipendenti originariamente full-time poi trasformati in part-time, o a tempo determinato in servizio all’1.1.2026 destinati all’indennità.',
    norma: 'Art. 60, CCNL 23.02.2026',
    percheServe: 'serve per individuare il numero di dipendenti dell\'Area Operatori da computare interamente per la decurtazione.',
    obbligatorieta: 'CONDIZIONALE',
    destinatarioSuggerito: 'Ufficio Personale',
    includeWhen: (s) => (s.ente.annoRiferimento || 2026) === 2026 && s.conglobamentoArt60.mode === 'guided'
  },
  {
    stepId: 5,
    stepTitle: 'Conglobamento comparto art. 60',
    field: 'conglobamentoArt60.partTimeNativoFte.OPERATORE',
    label: 'Area Operatori - FTE complessivo dei part-time nativi al 1° gennaio 2026',
    descrizione: 'FTE complessivo dei dipendenti assunti originariamente a tempo parziale all\'1.1.2026.',
    norma: 'Art. 60, CCNL 23.02.2026',
    percheServe: 'serve per riproporzionare la quota part-time nativa dell\'Area Operatori ai fini della riduzione stabile del Fondo.',
    obbligatorieta: 'CONDIZIONALE',
    destinatarioSuggerito: 'Ufficio Personale',
    includeWhen: (s) => (s.ente.annoRiferimento || 2026) === 2026 && s.conglobamentoArt60.mode === 'guided'
  },
  {
    stepId: 5,
    stepTitle: 'Conglobamento comparto art. 60',
    field: 'conglobamentoArt60.fullTimeTrasformatoPartTime.OPERATORE',
    label: 'Area Operatori - full-time trasformato in part-time da computare per intero',
    descrizione: 'Dipendenti assunti a tempo pieno e successivamente trasformati in part-time al 1° gennaio 2026.',
    norma: 'Art. 60, CCNL 23.02.2026',
    percheServe: 'serve per includere a quota piena i dipendenti ex full-time dell\'Area Operatori senza applicazione del riproporzionamento part-time.',
    obbligatorieta: 'CONDIZIONALE',
    destinatarioSuggerito: 'Ufficio Personale',
    includeWhen: (s) => (s.ente.annoRiferimento || 2026) === 2026 && s.conglobamentoArt60.mode === 'guided'
  },
  // AREA OPERATORE ESPERTO
  {
    stepId: 5,
    stepTitle: 'Conglobamento comparto art. 60',
    field: 'conglobamentoArt60.personaleInteroArea.OPERATORE_ESPERTO',
    label: 'Area Operatori Esperti - personale computato per intero al 1° gennaio 2026',
    descrizione: 'Dipendenti a tempo pieno, dipendenti originariamente full-time poi trasformati in part-time, o a tempo determinato in servizio all’1.1.2026 destinati all’indennità.',
    norma: 'Art. 60, CCNL 23.02.2026',
    percheServe: 'serve per individuare il numero di dipendenti dell\'Area Operatori Esperti da computare interamente per la decurtazione.',
    obbligatorieta: 'CONDIZIONALE',
    destinatarioSuggerito: 'Ufficio Personale',
    includeWhen: (s) => (s.ente.annoRiferimento || 2026) === 2026 && s.conglobamentoArt60.mode === 'guided'
  },
  {
    stepId: 5,
    stepTitle: 'Conglobamento comparto art. 60',
    field: 'conglobamentoArt60.partTimeNativoFte.OPERATORE_ESPERTO',
    label: 'Area Operatori Esperti - FTE complessivo dei part-time nativi al 1° gennaio 2026',
    descrizione: 'FTE complessivo dei dipendenti assunti originariamente a tempo parziale all\'1.1.2026.',
    norma: 'Art. 60, CCNL 23.02.2026',
    percheServe: 'serve per riproporzionare la quota part-time nativa dell\'Area Operatori Esperti ai fini della riduzione stabile del Fondo.',
    obbligatorieta: 'CONDIZIONALE',
    destinatarioSuggerito: 'Ufficio Personale',
    includeWhen: (s) => (s.ente.annoRiferimento || 2026) === 2026 && s.conglobamentoArt60.mode === 'guided'
  },
  {
    stepId: 5,
    stepTitle: 'Conglobamento comparto art. 60',
    field: 'conglobamentoArt60.fullTimeTrasformatoPartTime.OPERATORE_ESPERTO',
    label: 'Area Operatori Esperti - full-time trasformato in part-time da computare per intero',
    descrizione: 'Dipendenti assunti a tempo pieno e successivamente trasformati in part-time al 1° gennaio 2026.',
    norma: 'Art. 60, CCNL 23.02.2026',
    percheServe: 'serve per includere a quota piena i dipendenti ex full-time dell\'Area Operatori Esperti senza applicazione del riproporzionamento part-time.',
    obbligatorieta: 'CONDIZIONALE',
    destinatarioSuggerito: 'Ufficio Personale',
    includeWhen: (s) => (s.ente.annoRiferimento || 2026) === 2026 && s.conglobamentoArt60.mode === 'guided'
  },
  // AREA ISTRUTTORE
  {
    stepId: 5,
    stepTitle: 'Conglobamento comparto art. 60',
    field: 'conglobamentoArt60.personaleInteroArea.ISTRUTTORE',
    label: 'Area Istruttori - personale computato per intero al 1° gennaio 2026',
    descrizione: 'Dipendenti a tempo pieno, dipendenti originariamente full-time poi trasformati in part-time, o a tempo determinato in servizio all’1.1.2026 destinati all’indennità.',
    norma: 'Art. 60, CCNL 23.02.2026',
    percheServe: 'serve per individuare il numero di dipendenti dell\'Area Istruttori da computare interamente per la decurtazione.',
    obbligatorieta: 'CONDIZIONALE',
    destinatarioSuggerito: 'Ufficio Personale',
    includeWhen: (s) => (s.ente.annoRiferimento || 2026) === 2026 && s.conglobamentoArt60.mode === 'guided'
  },
  {
    stepId: 5,
    stepTitle: 'Conglobamento comparto art. 60',
    field: 'conglobamentoArt60.partTimeNativoFte.ISTRUTTORE',
    label: 'Area Istruttori - FTE complessivo dei part-time nativi al 1° gennaio 2026',
    descrizione: 'FTE complessivo dei dipendenti assunti originariamente a tempo parziale all\'1.1.2026.',
    norma: 'Art. 60, CCNL 23.02.2026',
    percheServe: 'serve per riproporzionare la quota part-time nativa dell\'Area Istruttori ai fini della riduzione stabile del Fondo.',
    obbligatorieta: 'CONDIZIONALE',
    destinatarioSuggerito: 'Ufficio Personale',
    includeWhen: (s) => (s.ente.annoRiferimento || 2026) === 2026 && s.conglobamentoArt60.mode === 'guided'
  },
  {
    stepId: 5,
    stepTitle: 'Conglobamento comparto art. 60',
    field: 'conglobamentoArt60.fullTimeTrasformatoPartTime.ISTRUTTORE',
    label: 'Area Istruttori - full-time trasformato in part-time da computare per intero',
    descrizione: 'Dipendenti assunti a tempo pieno e successivamente trasformati in part-time al 1° gennaio 2026.',
    norma: 'Art. 60, CCNL 23.02.2026',
    percheServe: 'serve per includere a quota piena i dipendenti ex full-time dell\'Area Istruttori senza applicazione del riproporzionamento part-time.',
    obbligatorieta: 'CONDIZIONALE',
    destinatarioSuggerito: 'Ufficio Personale',
    includeWhen: (s) => (s.ente.annoRiferimento || 2026) === 2026 && s.conglobamentoArt60.mode === 'guided'
  },
  // AREA FUNZIONARIO EQ
  {
    stepId: 5,
    stepTitle: 'Conglobamento comparto art. 60',
    field: 'conglobamentoArt60.personaleInteroArea.FUNZIONARIO_EQ',
    label: 'Area Funzionari ed Elevata Qualificazione - personale computato per intero al 1° gennaio 2026',
    descrizione: 'Dipendenti a tempo pieno, dipendenti originariamente full-time poi trasformati in part-time, o a tempo determinato in servizio all’1.1.2026 destinati all’indennità.',
    norma: 'Art. 60, CCNL 23.02.2026',
    percheServe: 'serve per individuare il numero di dipendenti dell\'Area Funzionari ed EQ da computare interamente per la decurtazione.',
    obbligatorieta: 'CONDIZIONALE',
    destinatarioSuggerito: 'Ufficio Personale',
    includeWhen: (s) => (s.ente.annoRiferimento || 2026) === 2026 && s.conglobamentoArt60.mode === 'guided'
  },
  {
    stepId: 5,
    stepTitle: 'Conglobamento comparto art. 60',
    field: 'conglobamentoArt60.partTimeNativoFte.FUNZIONARIO_EQ',
    label: 'Area Funzionari ed Elevata Qualificazione - FTE complessivo dei part-time nativi al 1° gennaio 2026',
    descrizione: 'FTE complessivo dei dipendenti assunti originariamente a tempo parziale all\'1.1.2026.',
    norma: 'Art. 60, CCNL 23.02.2026',
    percheServe: 'serve per riproporzionare la quota part-time nativa dell\'Area Funzionari ed EQ ai fini della riduzione stabile del Fondo.',
    obbligatorieta: 'CONDIZIONALE',
    destinatarioSuggerito: 'Ufficio Personale',
    includeWhen: (s) => (s.ente.annoRiferimento || 2026) === 2026 && s.conglobamentoArt60.mode === 'guided'
  },
  {
    stepId: 5,
    stepTitle: 'Conglobamento comparto art. 60',
    field: 'conglobamentoArt60.fullTimeTrasformatoPartTime.FUNZIONARIO_EQ',
    label: 'Area Funzionari ed Elevata Qualificazione - full-time trasformato in part-time da computare per intero',
    descrizione: 'Dipendenti assunti a tempo pieno e successivamente trasformati in part-time al 1° gennaio 2026.',
    norma: 'Art. 60, CCNL 23.02.2026',
    percheServe: 'serve per includere a quota piena i dipendenti ex full-time dell\'Area Funzionari ed EQ senza applicazione del riproporzionamento part-time.',
    obbligatorieta: 'CONDIZIONALE',
    destinatarioSuggerito: 'Ufficio Personale',
    includeWhen: (s) => (s.ente.annoRiferimento || 2026) === 2026 && s.conglobamentoArt60.mode === 'guided'
  },
  // MANUAL FIELD
  {
    stepId: 5,
    stepTitle: 'Conglobamento comparto art. 60',
    field: 'conglobamentoArt60.valoreManuale',
    label: 'Valore manuale riduzione conglobamento indennità di comparto',
    descrizione: 'Valore inserito direttamente se selezionata la modalità manuale.',
    norma: 'Art. 60, CCNL 23.02.2026',
    percheServe: 'serve per specificare direttamente l\'importo economico della riduzione permanente del Fondo in caso di calcolo manuale.',
    obbligatorieta: 'CONDIZIONALE',
    destinatarioSuggerito: 'Ufficio Personale',
    includeWhen: (s) => s.conglobamentoArt60.mode === 'manual'
  },
  {
    stepId: 5,
    stepTitle: 'Conglobamento comparto art. 60',
    field: 'conglobamentoArt60.notaManuale',
    label: 'Motivazione per inserimento manuale',
    descrizione: 'Nota obbligatoria se viene usato il valore manuale.',
    norma: 'Art. 60, CCNL 23.02.2026',
    percheServe: 'serve per documentare la motivazione tecnica o l\'atto amministrativo che giustifica l\'inserimento manuale in deroga.',
    obbligatorieta: 'CONDIZIONALE',
    destinatarioSuggerito: 'Ufficio Personale',
    includeWhen: (s) => s.conglobamentoArt60.mode === 'manual'
  },
  // CONSOLIDATO FIELD
  {
    stepId: 5,
    stepTitle: 'Conglobamento comparto art. 60',
    field: 'conglobamentoArt60.valoreConsolidato2026',
    label: 'Valore conglobamento consolidato 2026',
    descrizione: 'Il calcolo si effettua con riferimento al personale destinatario dell’indennità al 1° gennaio 2026. Il valore determinato nel 2026 si consolida negli anni successivi.',
    norma: 'Art. 60, CCNL 23.02.2026',
    percheServe: 'serve per inserire direttamente la decurtazione permanente già consolidata nel Fondo a far data dal 2026, evitando ricalcoli del personale.',
    obbligatorieta: 'CONDIZIONALE',
    destinatarioSuggerito: 'Ufficio Personale',
    includeWhen: (s) => (s.ente.annoRiferimento || 2026) > 2026
  },

  // ── STEP 6: STRAORDINARIO ─────────────────────────────────────────────────
  {
    stepId: 6,
    stepTitle: 'Fondo lavoro straordinario',
    field: 'straordinario.fondoStraordinarioOrdinarioAnnoCorrente',
    label: 'Fondo straordinario ordinario stanziato per l\'anno corrente',
    descrizione: 'Importo del Fondo lavoro straordinario ordinario previsto per il corrente esercizio.',
    norma: 'Art. 14, CCNL 23.02.2026 / Art. 23, comma 2, D.Lgs. 75/2017',
    percheServe: 'serve per stabilire lo stanziamento ordinario per il lavoro straordinario nell\'anno corrente da sottoporre a limite.',
    obbligatorieta: 'OBBLIGATORIO',
    destinatarioSuggerito: 'Ufficio Personale'
  },
  {
    stepId: 6,
    stepTitle: 'Fondo lavoro straordinario',
    field: 'straordinario.riduzioneStabileStraordinarioArt67',
    label: 'Riduzione stabile fondo straordinario destinata a FRD (Art. 67)',
    descrizione: 'Riduzione stabile del fondo straordinario spostata in parte stabile del Fondo decentrato.',
    norma: 'Art. 67, CCNL 21.05.2018',
    percheServe: 'serve per quantificare lo spostamento stabile di risorse dallo straordinario al Fondo risorse decentrate.',
    obbligatorieta: 'OPZIONALE',
    destinatarioSuggerito: 'Ufficio Personale'
  },
  {
    stepId: 6,
    stepTitle: 'Fondo lavoro straordinario',
    field: 'straordinario.stanziamentoStraordinarioOrdinarioAnnoPrecedente',
    label: 'Stanziamento straordinario ordinario anno precedente',
    descrizione: 'Stanziamento dell\'anno precedente per il calcolo delle economie.',
    norma: 'Art. 67, comma 3, CCNL 23.02.2026',
    percheServe: 'serve per impostare la base di raffronto dell\'anno precedente necessaria per determinare l\'insorgenza di economie.',
    obbligatorieta: 'OPZIONALE',
    destinatarioSuggerito: 'Ufficio Ragioneria'
  },
  {
    stepId: 6,
    stepTitle: 'Fondo lavoro straordinario',
    field: 'straordinario.spesaStraordinarioOrdinarioAnnoPrecedente',
    label: 'Spesa effettiva straordinario ordinario anno precedente',
    descrizione: 'Spesa effettiva registrata nell\'anno precedente.',
    norma: 'Art. 67, comma 3, CCNL 23.02.2026',
    percheServe: 'serve per rilevare l\'effettivo consuntivo speso dello straordinario e calcolare le economie di bilancio.',
    obbligatorieta: 'OPZIONALE',
    destinatarioSuggerito: 'Ufficio Ragioneria'
  },
  {
    stepId: 6,
    stepTitle: 'Fondo lavoro straordinario',
    field: 'straordinario.economieStraordinarioCertificate',
    label: 'Economie da straordinario certificate da riversare nel Fondo',
    descrizione: 'Economie certificate del lavoro straordinario destinate a incrementare la parte variabile del Fondo.',
    norma: 'Art. 67, comma 3, CCNL 23.02.2026',
    percheServe: 'serve per disporre dell\'attestazione ufficiale dei revisori sulle somme non spese da far confluire a fondo.',
    obbligatorieta: 'OPZIONALE',
    destinatarioSuggerito: 'Ufficio Ragioneria'
  },

  // ── STEP 7: INCREMENTO PNRR ───────────────────────────────────────────────
  {
    stepId: 7,
    stepTitle: 'Incremento PNRR',
    field: 'pnrr.soggettoAttuatorePnrr',
    label: 'Ente soggetto attuatore/titolare di interventi PNRR',
    descrizione: 'Indicare se l\'ente gestisce interventi/progetti finanziati dal PNRR (Sì/No).',
    norma: 'Art. 8, comma 3, D.L. 13/2023',
    percheServe: 'serve per verificare la condizione di applicabilità del calcolo del limite massimo PNRR.',
    obbligatorieta: 'OBBLIGATORIO',
    destinatarioSuggerito: 'Ufficio Personale',
    includeWhen: (s) => s.pnrr.soggettoAttuatorePnrr !== false
  },
  {
    stepId: 7,
    stepTitle: 'Incremento PNRR',
    field: 'pnrr.componenteStabileFondoDipendenti2016',
    label: 'Componente stabile Fondo dipendenti 2016',
    descrizione: 'Valore delle risorse stabili del Fondo dipendenti 2016 per il calcolo della quota PNRR (max 5%).',
    norma: 'Art. 8, comma 3, D.L. 13/2023',
    percheServe: 'serve per determinare il tetto massimo del 5% di incremento del salario accessorio per il personale del comparto.',
    obbligatorieta: 'OBBLIGATORIO',
    destinatarioSuggerito: 'Ufficio Personale',
    includeWhen: (s) => s.pnrr.soggettoAttuatorePnrr !== false
  },
  {
    stepId: 7,
    stepTitle: 'Incremento PNRR',
    field: 'pnrr.componenteStabileFondoDirigenza2016',
    label: 'Componente stabile Fondo dirigenza 2016',
    descrizione: 'Valore delle risorse stabili del Fondo dirigenti 2016 (richiesto solo se presente la dirigenza).',
    norma: 'Art. 8, comma 3, D.L. 13/2023',
    percheServe: 'serve per determinare il tetto massimo del 5% di incremento del salario accessorio per il personale dirigente.',
    obbligatorieta: 'CONDIZIONALE',
    destinatarioSuggerito: 'Ufficio Personale',
    includeWhen: (s) => s.pnrr.soggettoAttuatorePnrr !== false && !!s.ente.hasDirigenza
  },
  {
    stepId: 7,
    stepTitle: 'Incremento PNRR',
    field: 'pnrr.equilibrioEsercizioPrecedente',
    label: 'Equilibrio di bilancio esercizio precedente',
    descrizione: 'Verifica del rispetto del pareggio e dell\'equilibrio di bilancio (Sì/No).',
    norma: 'Art. 8, commi 3 e 4, D.L. 13/2023',
    percheServe: 'serve per attestare l\'equilibrio di bilancio dell\'esercizio precedente quale requisito normativo di applicabilità.',
    obbligatorieta: 'OBBLIGATORIO',
    destinatarioSuggerito: 'Ufficio Ragioneria',
    includeWhen: (s) => s.pnrr.soggettoAttuatorePnrr !== false
  },
  {
    stepId: 7,
    stepTitle: 'Incremento PNRR',
    field: 'pnrr.parametriDebitoCommercialeEsercizioPrecedente',
    label: 'Rispetto parametri debito commerciale e ritardi pagamenti',
    descrizione: 'Verifica della regolarità nei pagamenti commerciali delle transazioni (Sì/No).',
    norma: 'Art. 8, commi 3 e 4, D.L. 13/2023',
    percheServe: 'serve per verificare il rispetto dei parametri di tempestività dei pagamenti e debito commerciale quale requisito abilitante.',
    obbligatorieta: 'OBBLIGATORIO',
    destinatarioSuggerito: 'Ufficio Ragioneria',
    includeWhen: (s) => s.pnrr.soggettoAttuatorePnrr !== false
  },
  {
    stepId: 7,
    stepTitle: 'Incremento PNRR',
    field: 'pnrr.incidenzaSalarioAccessorioScelta',
    label: 'Modalità calcolo incidenza salario accessorio',
    descrizione: 'Metodo: "diretto" per inserire direttamente la percentuale, "assistito" per inserire spesa e personale.',
    norma: 'Art. 8, commi 3 e 4, D.L. 13/2023',
    percheServe: 'serve per definire l\'approccio di compilazione del calcolo dell\'incidenza del salario accessorio.',
    obbligatorieta: 'OBBLIGATORIO',
    destinatarioSuggerito: 'Ufficio Ragioneria',
    includeWhen: (s) => s.pnrr.soggettoAttuatorePnrr !== false
  },
  {
    stepId: 7,
    stepTitle: 'Incremento PNRR',
    field: 'pnrr.incidenzaSalarioAccessorioPercentuale',
    label: 'Incidenza salario accessorio su spesa personale (percentuale)',
    descrizione: 'Valore percentuale inserito direttamente (limite 8%).',
    norma: 'Art. 8, commi 3 e 4, D.L. 13/2023',
    percheServe: 'serve per verificare il rispetto della soglia massima dell\'8% dell\'incidenza del salario accessorio sulla spesa del personale.',
    obbligatorieta: 'CONDIZIONALE',
    destinatarioSuggerito: 'Ufficio Ragioneria',
    includeWhen: (s) => s.pnrr.soggettoAttuatorePnrr !== false && s.pnrr.incidenzaSalarioAccessorioScelta === 'diretto'
  },
  {
    stepId: 7,
    stepTitle: 'Incremento PNRR',
    field: 'pnrr.salarioAccessorioIndicatori',
    label: 'Spesa salario accessorio per indicatori',
    descrizione: 'Spesa per salario accessorio erogata (usata per il calcolo dell\'incidenza).',
    norma: 'Art. 8, commi 3 e 4, D.L. 13/2023',
    percheServe: 'serve per determinare in modo assistito la quota numeratore spesa accessoria dell\'anno precedente.',
    obbligatorieta: 'CONDIZIONALE',
    destinatarioSuggerito: 'Ufficio Ragioneria',
    includeWhen: (s) => s.pnrr.soggettoAttuatorePnrr !== false && s.pnrr.incidenzaSalarioAccessorioScelta === 'assistito'
  },
  {
    stepId: 7,
    stepTitle: 'Incremento PNRR',
    field: 'pnrr.spesaPersonaleIndicatori',
    label: 'Spesa complessiva personale per indicatori',
    descrizione: 'Spesa complessiva del personale (usata per il calcolo dell\'incidenza).',
    norma: 'Art. 8, commi 3 e 4, D.L. 13/2023',
    percheServe: 'serve per determinare in modo assistito la quota denominatore spesa totale del personale dell\'anno precedente.',
    obbligatorieta: 'CONDIZIONALE',
    destinatarioSuggerito: 'Ufficio Ragioneria',
    includeWhen: (s) => s.pnrr.soggettoAttuatorePnrr !== false && s.pnrr.incidenzaSalarioAccessorioScelta === 'assistito'
  },
  {
    stepId: 7,
    stepTitle: 'Incremento PNRR',
    field: 'pnrr.rendicontoApprovatoTermini',
    label: 'Rendiconto anno precedente approvato nei termini dall\'organo consiliare',
    descrizione: 'Verifica dell\'approvazione nei termini di legge del rendiconto consiliare (Sì/No).',
    norma: 'Art. 8, commi 3 e 4, D.L. 13/2023',
    percheServe: 'serve per confermare che l\'approvazione del rendiconto dell\'anno precedente sia avvenuta entro i termini fissati dalla legge.',
    obbligatorieta: 'OBBLIGATORIO',
    destinatarioSuggerito: 'Ufficio Ragioneria',
    includeWhen: (s) => s.pnrr.soggettoAttuatorePnrr !== false
  }
];
