import { Wizard2026EntityType } from '../types';

export type ExcelCellType = 'input_required' | 'input_optional' | 'calculated';
export type ExcelDataType = 'string' | 'number' | 'boolean' | 'select';

export interface ExcelFieldSchema {
  label: string;
  key: string; // Es. 'ente.entityType', 'dl25.stipendiTabellari2023NonDirigenti'
  type: ExcelDataType;
  cellType: ExcelCellType;
  options?: string[];
  note: string;
}

export interface ExcelSheetSchema {
  sheetName: string;
  fields: ExcelFieldSchema[];
}

export const ENTITY_TYPE_LABELS: Record<Wizard2026EntityType, string> = {
  COMUNE: 'Comune',
  PROVINCIA: 'Provincia',
  CITTA_METROPOLITANA: 'Città Metropolitana',
  REGIONE: 'Regione',
  UNIONE_COMUNI: 'Unione di Comuni',
  COMUNITA_MONTANA: 'Comunità Montana',
  COMUNITA_ISOLANA_O_ARCIPELAGO: 'Comunità Isolana o Arcipelago',
  CAMERA_COMMERCIO: 'Camera di Commercio',
  ENTE_REGIONALE: 'Ente Regionale',
  ENTE_PARCO: 'Ente Parco',
  CONSORZIO: 'Consorzio',
  ASP: 'Azienda Servizi alla Persona (ASP)',
  AZIENDA_SPECIALE: 'Azienda Speciale',
  ISTITUZIONE: 'Istituzione',
  ALTRO_ENTE_STRUMENTALE: 'Altro Ente Strumentale',
  ALTRO: 'Altra Tipologia (Verifica Manuale)',
};

export const REVERSE_ENTITY_TYPE_LABELS = Object.entries(ENTITY_TYPE_LABELS).reduce(
  (acc, [k, v]) => ({ ...acc, [v]: k as Wizard2026EntityType }),
  {} as Record<string, Wizard2026EntityType>
);

export const wizard2026ExcelSchema: ExcelSheetSchema[] = [
  {
    sheetName: 'Dati Ente',
    fields: [
      {
        label: 'Denominazione Ente',
        key: 'ente.denominazioneEnte',
        type: 'string',
        cellType: 'input_required',
        note: 'Dato acquisito dall\'ente attivo selezionato.',
      },
      {
        label: 'Anno di Riferimento Istruttoria',
        key: 'ente.annoRiferimento',
        type: 'number',
        cellType: 'input_required',
        note: 'Anno per cui si compila il wizard.',
      },
      {
        label: 'Qualificazione Giuridica (Tipologia Ente)',
        key: 'ente.entityType',
        type: 'select',
        cellType: 'input_required',
        options: Object.values(ENTITY_TYPE_LABELS),
        note: 'Seleziona una tipologia dall\'elenco (Comune, Provincia, Unione, ecc.).',
      },
      {
        label: 'Presenza della Dirigenza',
        key: 'ente.hasDirigenza',
        type: 'boolean',
        cellType: 'input_required',
        note: 'Indicare se l\'ente ha o meno personale dirigente in organico (Sì/No).',
      },
      {
        label: 'Ente in Stato di Dissesto Finanziario',
        key: 'ente.isDissesto',
        type: 'boolean',
        cellType: 'input_required',
        note: 'Indicare se l\'ente si trova in stato di dissesto finanziario (Sì/No).',
      },
      {
        label: 'Ente in Condizioni di Deficitarietà Strutturale',
        key: 'ente.isStrutturalmenteDeficitario',
        type: 'boolean',
        cellType: 'input_required',
        note: 'Indicare se l\'ente è strutturalmente deficitario (Sì/No).',
      },
      {
        label: 'Ente in Piano di Riequilibrio Finanziario Pluriennale',
        key: 'ente.isPianoRiequilibrio',
        type: 'boolean',
        cellType: 'input_required',
        note: 'Indicare se l\'ente ha un piano di riequilibrio deliberato (Sì/No).',
      },
      {
        label: 'Comune in Prima Fascia di Virtuosità D.L. 34/2019',
        key: 'ente.isPrimaFasciaDl34',
        type: 'boolean',
        cellType: 'input_optional',
        note: 'Solo per i Comuni. Indica se il Comune appartiene alla fascia di massima virtuosità assunzioni (Sì/No).',
      },
      {
        label: 'Equilibrio di Bilancio Pluriennale Asseverato',
        key: 'ente.isEquilibrioPluriennaleAsseverato',
        type: 'boolean',
        cellType: 'input_required',
        note: 'Indicare se gli equilibri di bilancio pluriennali sono regolarmente asseverati (Sì/No).',
      },
      {
        label: 'Approvazione COSFEL ottenuta per le assunzioni/spesa',
        key: 'ente.hasApprovazioneCosfel',
        type: 'boolean',
        cellType: 'input_optional',
        note: 'Se l\'ente ha criticità finanziarie (dissesto/deficitario/riequilibrio), indicare se è stata ottenuta l\'approvazione COSFEL (Sì/No).',
      },
    ],
  },
  {
    sheetName: 'Art. 23 Limite',
    fields: [
      {
        label: 'Limite Complessivo Trattamento Accessorio 2016 Certificato',
        key: 'art23.limite2016CertificatoEnte',
        type: 'number',
        cellType: 'input_required',
        note: 'Il tetto storico complessivo del trattamento accessorio per l\'anno 2016 (certificato dai revisori).',
      },
      {
        label: 'di cui: Fondo risorse decentrate personale dipendente 2016',
        key: 'art23.fondoPersonaleDipendente2016',
        type: 'number',
        cellType: 'input_optional',
        note: 'Quota parte del tetto 2016 destinata al personale non dirigente.',
      },
      {
        label: 'di cui: Risorse destinate alle Elevate Qualificazioni (ex P.O.) 2016',
        key: 'art23.fondoEqPo2016',
        type: 'number',
        cellType: 'input_optional',
        note: 'Quota parte del tetto 2016 destinata alle Posizioni Organizzative / Elevate Qualificazioni.',
      },
      {
        label: 'di cui: Fondo personale dirigente 2016',
        key: 'art23.fondoDirigenza2016',
        type: 'number',
        cellType: 'input_optional',
        note: 'Quota parte del tetto 2016 destinata ai dirigenti (se presente la dirigenza).',
      },
      {
        label: 'di cui: Risorse segretario comunale/provinciale 2016',
        key: 'art23.risorseSegretario2016',
        type: 'number',
        cellType: 'input_optional',
        note: 'Quota parte del tetto 2016 per la retribuzione di posizione e risultato del segretario comunale.',
      },
      {
        label: 'di cui: Fondo lavoro straordinario 2016 (soggetto al limite)',
        key: 'art23.fondoStraordinario2016',
        type: 'number',
        cellType: 'input_optional',
        note: 'Quota parte del tetto 2016 per il lavoro straordinario.',
      },
      {
        label: 'di cui: Altre voci accessorie soggette al limite 2016',
        key: 'art23.altreVoci2016Soggette',
        type: 'number',
        cellType: 'input_optional',
        note: 'Eventuali altre voci accessorie erogate fuori dai fondi ma soggette al limite nel 2016.',
      },
      {
        label: 'Fondo dipendenti 2018 soggetto al limite (valore storico)',
        key: 'art23.fondoDipendenti2018Soggetto',
        type: 'number',
        cellType: 'input_optional',
        note: 'Necessario per il calcolo dell\'adeguamento del valore medio pro capite (Art. 33 D.L. 34/2019).',
      },
      {
        label: 'Risorse P.O./E.Q. 2018 soggette al limite (valore storico)',
        key: 'art23.risorsePoEq2018Soggette',
        type: 'number',
        cellType: 'input_optional',
        note: 'Valore delle risorse per posizioni organizzative destinate nel 2018.',
      },
      {
        label: 'Personale in servizio al 31/12/2018 (valore medio pro capite)',
        key: 'art23.personaleServizio31122018',
        type: 'number',
        cellType: 'input_optional',
        note: 'Consistenza di personale in servizio a fine 2018 utilizzata come base pro-capite.',
      },
      {
        label: 'Personale previsto nell\'anno di riferimento (PIAO)',
        key: 'art23.personalePrevisto2026Piao',
        type: 'number',
        cellType: 'input_optional',
        note: 'Consistenza programmata nel PIAO per l\'anno di riferimento.',
      },
      {
        label: 'Usa inserimento manuale dipendenti equivalenti per Art. 23',
        key: 'art23.usaCalcoloManualePersonaleArt23',
        type: 'boolean',
        cellType: 'input_required',
        note: 'Consente di inserire direttamente i dipendenti equivalenti per il ricalcolo del limite (Sì/No).',
      },
      {
        label: 'Valore manuale dipendenti equivalenti 2018',
        key: 'art23.manualDipendentiEquivalenti2018',
        type: 'number',
        cellType: 'input_optional',
        note: 'Valore manuale dipendenti equivalenti per il 2018.',
      },
      {
        label: 'Valore manuale dipendenti equivalenti anno riferimento',
        key: 'art23.manualDipendentiEquivalenti2026',
        type: 'number',
        cellType: 'input_optional',
        note: 'Valore manuale dipendenti equivalenti per l\'anno corrente.',
      },
      {
        label: 'Personale a tempo indeterminato anno riferimento',
        key: 'art23.personaleTempoIndeterminato2026',
        type: 'number',
        cellType: 'input_optional',
        note: 'Organico a tempo indeterminato programmato.',
      },
      {
        label: 'Personale a tempo determinato anno riferimento',
        key: 'art23.personaleTempoDeterminato2026',
        type: 'number',
        cellType: 'input_optional',
        note: 'Organico a tempo determinato programmato.',
      },
      {
        label: 'Assunzioni previste anno riferimento',
        key: 'art23.assunzioniPreviste2026',
        type: 'number',
        cellType: 'input_optional',
        note: 'Totale assunzioni programmate nell\'anno.',
      },
      {
        label: 'Cessazioni previste anno riferimento',
        key: 'art23.cessazioniPreviste2026',
        type: 'number',
        cellType: 'input_optional',
        note: 'Totale cessazioni programmate nell\'anno.',
      },
    ],
  },
  {
    sheetName: 'D.L. 25-2025',
    fields: [
      {
        label: 'Spesa per stipendi tabellari 2023 del personale non dirigente',
        key: 'dl25.stipendiTabellari2023NonDirigenti',
        type: 'number',
        cellType: 'input_required',
        note: 'Spesa sostenuta nel 2023 per gli stipendi tabellari del personale non dirigente (esclusi oneri e IRAP).',
      },
      {
        label: 'Consistenza Fondo risorse decentrate parte stabile dell’anno precedente',
        key: 'dl25.fondoStabile2025Certificato',
        type: 'number',
        cellType: 'input_required',
        note: 'La consistenza della sola parte stabile del Fondo risorse decentrate dell\'anno precedente (per istruttoria 2026 il dato da inserire è quello del 2025. Per istruttorie successive, il dato deve riferirsi all’anno precedente all’anno di riferimento) certificata dai revisori.',
      },
      {
        label: 'Budget Elevate Qualificazioni dell’anno precedente',
        key: 'dl25.budgetEq2025',
        type: 'number',
        cellType: 'input_required',
        note: 'Risorse complessivamente destinate alle Elevate Qualificazioni dell\'anno precedente (per istruttoria 2026 il dato da inserire è quello del 2025. Per istruttorie successive, il dato deve riferirsi all’anno precedente all’anno di riferimento) certificate.',
      },
      {
        label: 'Altre risorse stabili dell\'anno precedente da sottrarre',
        key: 'dl25.altreRisorse2025DaSottrarre',
        type: 'number',
        cellType: 'input_optional',
        note: 'Altre risorse stabili erogate nell\'anno precedente esterne al Fondo che vanno sottratte in base alle circolari applicative.',
      },
      {
        label: 'Quota massima trasferibile dagli enti aderenti',
        key: 'dl25.quotaTrasferitaAderentiDL25_2025',
        type: 'number',
        cellType: 'input_optional',
        note: 'Risorse trasferite per il finanziamento dei servizi associati o unificati dagli enti aderenti.',
      },
      {
        label: 'Popolazione residente (per Comuni)',
        key: 'dl25.popolazioneEnte',
        type: 'number',
        cellType: 'input_optional',
        note: 'Popolazione residente al 31/12 dell\'anno precedente.',
      },
      {
        label: 'Entrate correnti (Rendiconto anno N-1)',
        key: 'dl25.entrateCorrentiN1',
        type: 'number',
        cellType: 'input_optional',
        note: 'Entrate correnti per il calcolo degli indici di virtuosità (Rendiconto anno precedente).',
      },
      {
        label: 'Entrate correnti (Rendiconto anno N-2)',
        key: 'dl25.entrateCorrentiN2',
        type: 'number',
        cellType: 'input_optional',
        note: 'Entrate correnti (Rendiconto due anni precedenti).',
      },
      {
        label: 'Entrate correnti (Rendiconto anno N-3)',
        key: 'dl25.entrateCorrentiN3',
        type: 'number',
        cellType: 'input_optional',
        note: 'Entrate correnti (Rendiconto tre anni precedenti).',
      },
      {
        label: 'FCDE stanziato nel bilancio di previsione',
        key: 'dl25.fcdeStanziato',
        type: 'number',
        cellType: 'input_optional',
        note: 'Fondo Crediti di Dubbia Esigibilità stanziato nel bilancio di previsione corrente.',
      },
      {
        label: 'Spesa del personale dell\'ultimo rendiconto approvato',
        key: 'dl25.spesaPersonaleUltimoRendiconto',
        type: 'number',
        cellType: 'input_optional',
        note: 'Spesa totale del personale registrata a consuntivo.',
      },
      {
        label: 'Spesa del personale di riferimento storica (limite spesa)',
        key: 'dl25.limiteStoricoSpesaPersonale',
        type: 'number',
        cellType: 'input_optional',
        note: 'Valore limite storico per la spesa del personale dell\'ente.',
      },
      {
        label: 'Base di calcolo limite storico',
        key: 'dl25.baseCalcoloLimiteStorico',
        type: 'string',
        cellType: 'input_optional',
        note: 'Indicazione della norma o della base storica del limite di spesa del personale.',
      },
      {
        label: 'Spesa personale prevista anno riferimento (ante incremento)',
        key: 'dl25.spesaPersonalePrevista2026AnteIncremento',
        type: 'number',
        cellType: 'input_optional',
        note: 'Spesa complessiva prevista per il personale nell\'anno prima dell\'applicazione del D.L. 25.',
      },
      {
        label: 'Estremi autorizzazione COSFEL per D.L. 25',
        key: 'dl25.documentazioneCosfelDl25',
        type: 'string',
        cellType: 'input_optional',
        note: 'Indicare la delibera COSFEL autorizzativa se applicabile.',
      },
      {
        label: 'Presenza degli atti di tutti i comuni aderenti',
        key: 'dl25.attiComuniAderentiPresenti',
        type: 'boolean',
        cellType: 'input_optional',
        note: 'Solo per Unioni. Indica se tutti i comuni aderenti hanno deliberato il trasferimento (Sì/No).',
      },
      {
        label: 'Certificazione riduzione permanente fondi dei singoli comuni',
        key: 'dl25.riduzionePermanenteFondiComuniCertificata',
        type: 'boolean',
        cellType: 'input_optional',
        note: 'Solo per Unioni. Indica se i revisori hanno certificato la correlata riduzione stabile nei singoli bilanci (Sì/No).',
      },
      {
        label: 'Certificazione dei revisori dei singoli comuni',
        key: 'dl25.certificazioneRevisoriComuni',
        type: 'boolean',
        cellType: 'input_optional',
        note: 'Solo per Unioni. Indica il parere favorevole dei revisori degli enti aderenti (Sì/No).',
      },
    ],
  },
  {
    sheetName: 'CCNL 2026',
    fields: [
      {
        label: 'Monte Salari anno 2021 personale non dirigente',
        key: 'ccnl2026.monteSalari2021',
        type: 'number',
        cellType: 'input_required',
        note: 'Il monte salari 2021 del personale non dirigente (dichiarato in conto annuale) per il calcolo degli incrementi.',
      },
      {
        label: 'Monte Salari 2021 consolidato',
        key: 'ccnl2026.monteSalari2021Consolidato2026',
        type: 'number',
        cellType: 'input_optional',
        note: 'Monte Salari 2021 consolidato (trascinato dalle istruttorie precedenti).',
      },
      {
        label: 'Intero Fondo risorse decentrate anno 2024',
        key: 'ccnl2026.fondoRisorseDecentrate2024',
        type: 'number',
        cellType: 'input_required',
        note: 'Base di riparto per l\'incremento dello 0,22% destinato al Fondo risorse decentrate.',
      },
      {
        label: 'Intere risorse destinate alle Elevate Qualificazioni anno 2024',
        key: 'ccnl2026.risorseEQ2024',
        type: 'number',
        cellType: 'input_required',
        note: 'Base di riparto per l\'incremento dello 0,22% destinato alla retribuzione di posizione e risultato delle EQ.',
      },
      {
        label: 'Quota dello 0,22% che l’ente intende applicare nell’anno',
        key: 'ccnl2026.incremento022Anno',
        type: 'number',
        cellType: 'input_optional',
        note: 'La quota effettiva dello 0,22% che si intende stanziare (limite massimo teorico calcolato automaticamente).',
      },
    ],
  },
  {
    sheetName: 'Conglobamento Art. 60',
    fields: [
      {
        label: 'Modalità di inserimento',
        key: 'conglobamentoArt60.mode',
        type: 'select',
        cellType: 'input_required',
        options: ['guided', 'manual'],
        note: 'Modalità di inserimento: "guided" per calcolo basato sul personale, "manual" per inserimento manuale motivato.',
      },
      // Area Operatori
      {
        label: 'Area Operatori - personale computato per intero al 1° gennaio 2026',
        key: 'conglobamentoArt60.personaleInteroArea.OPERATORE',
        type: 'number',
        cellType: 'input_optional',
        note: 'Dipendenti a tempo pieno, dipendenti originariamente full-time poi trasformati in part-time, o a tempo determinato in servizio all’1.1.2026 destinatati all’indennità.',
      },
      {
        label: 'Area Operatori - FTE complessivo dei part-time nativi al 1° gennaio 2026',
        key: 'conglobamentoArt60.partTimeNativoFte.OPERATORE',
        type: 'number',
        cellType: 'input_optional',
        note: 'FTE (Full-Time Equivalent) complessivo dei dipendenti assunti originariamente a tempo parziale all\'1.1.2026 (es. per due dipendenti a 18 ore / 50%, inserire 1.0).',
      },
      {
        label: 'Area Operatori - full-time trasformato in part-time da computare per intero',
        key: 'conglobamentoArt60.fullTimeTrasformatoPartTime.OPERATORE',
        type: 'number',
        cellType: 'input_optional',
        note: 'Dipendenti assunti a tempo pieno e successivamente trasformati in part-time al 1° gennaio 2026 (da computare per intero).',
      },
      // Area Operatori Esperti
      {
        label: 'Area Operatori Esperti - personale computato per intero al 1° gennaio 2026',
        key: 'conglobamentoArt60.personaleInteroArea.OPERATORE_ESPERTO',
        type: 'number',
        cellType: 'input_optional',
        note: 'Dipendenti a tempo pieno, dipendenti originariamente full-time poi trasformati in part-time, o a tempo determinato in servizio all’1.1.2026 destinatati all’indennità.',
      },
      {
        label: 'Area Operatori Esperti - FTE complessivo dei part-time nativi al 1° gennaio 2026',
        key: 'conglobamentoArt60.partTimeNativoFte.OPERATORE_ESPERTO',
        type: 'number',
        cellType: 'input_optional',
        note: 'FTE (Full-Time Equivalent) complessivo dei dipendenti assunti originariamente a tempo parziale all\'1.1.2026 (es. per due dipendenti a 18 ore / 50%, inserire 1.0).',
      },
      {
        label: 'Area Operatori Esperti - full-time trasformato in part-time da computare per intero',
        key: 'conglobamentoArt60.fullTimeTrasformatoPartTime.OPERATORE_ESPERTO',
        type: 'number',
        cellType: 'input_optional',
        note: 'Dipendenti assunti a tempo pieno e successivamente trasformati in part-time al 1° gennaio 2026 (da computare per intero).',
      },
      // Area Istruttori
      {
        label: 'Area Istruttori - personale computato per intero al 1° gennaio 2026',
        key: 'conglobamentoArt60.personaleInteroArea.ISTRUTTORE',
        type: 'number',
        cellType: 'input_optional',
        note: 'Dipendenti a tempo pieno, dipendenti originariamente full-time poi trasformati in part-time, o a tempo determinato in servizio all’1.1.2026 destinatati all’indennità.',
      },
      {
        label: 'Area Istruttori - FTE complessivo dei part-time nativi al 1° gennaio 2026',
        key: 'conglobamentoArt60.partTimeNativoFte.ISTRUTTORE',
        type: 'number',
        cellType: 'input_optional',
        note: 'FTE (Full-Time Equivalent) complessivo dei dipendenti assunti originariamente a tempo parziale all\'1.1.2026 (es. per due dipendenti a 18 ore / 50%, inserire 1.0).',
      },
      {
        label: 'Area Istruttori - full-time trasformato in part-time da computare per intero',
        key: 'conglobamentoArt60.fullTimeTrasformatoPartTime.ISTRUTTORE',
        type: 'number',
        cellType: 'input_optional',
        note: 'Dipendenti assunti a tempo pieno e successivamente trasformati in part-time al 1° gennaio 2026 (da computare per intero).',
      },
      // Area Funzionari ed Elevata Qualificazione
      {
        label: 'Area Funzionari ed Elevata Qualificazione - personale computato per intero al 1° gennaio 2026',
        key: 'conglobamentoArt60.personaleInteroArea.FUNZIONARIO_EQ',
        type: 'number',
        cellType: 'input_optional',
        note: 'Dipendenti a tempo pieno, dipendenti originariamente full-time poi trasformati in part-time, o a tempo determinato in servizio all’1.1.2026 destinatati all’indennità.',
      },
      {
        label: 'Area Funzionari ed Elevata Qualificazione - FTE complessivo dei part-time nativi al 1° gennaio 2026',
        key: 'conglobamentoArt60.partTimeNativoFte.FUNZIONARIO_EQ',
        type: 'number',
        cellType: 'input_optional',
        note: 'FTE (Full-Time Equivalent) complessivo dei dipendenti assunti originariamente a tempo parziale all\'1.1.2026 (es. per due dipendenti a 18 ore / 50%, inserire 1.0).',
      },
      {
        label: 'Area Funzionari ed Elevata Qualificazione - full-time trasformato in part-time da computare per intero',
        key: 'conglobamentoArt60.fullTimeTrasformatoPartTime.FUNZIONARIO_EQ',
        type: 'number',
        cellType: 'input_optional',
        note: 'Dipendenti assunti a tempo pieno e successivamente trasformati in part-time al 1° gennaio 2026 (da computare per intero).',
      },
      {
        label: 'Valore manuale riduzione conglobamento indennità di comparto',
        key: 'conglobamentoArt60.valoreManuale',
        type: 'number',
        cellType: 'input_optional',
        note: 'Valore inserito direttamente se selezionata la modalità manuale.',
      },
      {
        label: 'Motivazione per inserimento manuale',
        key: 'conglobamentoArt60.notaManuale',
        type: 'string',
        cellType: 'input_optional',
        note: 'Nota obbligatoria se viene usato il valore manuale.',
      },
      {
        label: 'Valore conglobamento consolidato 2026',
        key: 'conglobamentoArt60.valoreConsolidato2026',
        type: 'number',
        cellType: 'input_optional',
        note: 'Il calcolo si effettua con riferimento al personale destinatario dell’indennità al 1° gennaio 2026. Il valore determinato nel 2026 si consolida negli anni successivi e non deve essere ricalcolato sul personale degli anni successivi, salvo correzione manuale motivata.',
      },
    ],
  },
  {
    sheetName: 'Straordinario',
    fields: [
      {
        label: 'Fondo straordinario ordinario stanziato per l\'anno corrente',
        key: 'straordinario.fondoStraordinarioOrdinarioAnnoCorrente',
        type: 'number',
        cellType: 'input_required',
        note: 'Importo del Fondo lavoro straordinario ordinario previsto per il corrente esercizio.',
      },
      {
        label: 'Riduzione stabile fondo straordinario destinata a FRD (Art. 67)',
        key: 'straordinario.riduzioneStabileStraordinarioArt67',
        type: 'number',
        cellType: 'input_optional',
        note: 'Riduzione stabile del fondo straordinario spostata in parte stabile del Fondo decentrato (Art. 67, CCNL 21.5.2018).',
      },
      {
        label: 'Stanziamento straordinario ordinario anno precedente',
        key: 'straordinario.stanziamentoStraordinarioOrdinarioAnnoPrecedente',
        type: 'number',
        cellType: 'input_optional',
        note: 'Stanziamento dell\'anno precedente per il calcolo delle economie.',
      },
      {
        label: 'Spesa effettiva straordinario ordinario anno precedente',
        key: 'straordinario.spesaStraordinarioOrdinarioAnnoPrecedente',
        type: 'number',
        cellType: 'input_optional',
        note: 'Spesa effettiva registrata nell\'anno precedente.',
      },
      {
        label: 'Economie da straordinario certificate da riversare nel Fondo',
        key: 'straordinario.economieStraordinarioCertificate',
        type: 'number',
        cellType: 'input_optional',
        note: 'Economie certificate del lavoro straordinario destinate a incrementare la parte variabile del Fondo.',
      },
    ],
  },
  {
    sheetName: 'PNRR',
    fields: [
      {
        label: 'Ente soggetto attuatore/titolare di interventi PNRR',
        key: 'pnrr.soggettoAttuatorePnrr',
        type: 'boolean',
        cellType: 'input_required',
        note: 'Indicare se l\'ente gestisce interventi/progetti finanziati dal PNRR (Sì/No).',
      },
      {
        label: 'Componente stabile Fondo dipendenti 2016',
        key: 'pnrr.componenteStabileFondoDipendenti2016',
        type: 'number',
        cellType: 'input_required',
        note: 'Valore delle risorse stabili del Fondo dipendenti 2016 per il calcolo della quota PNRR (max 5%).',
      },
      {
        label: 'Componente stabile Fondo dirigenza 2016',
        key: 'pnrr.componenteStabileFondoDirigenza2016',
        type: 'number',
        cellType: 'input_optional',
        note: 'Valore delle risorse stabili del Fondo dirigenti 2016 (richiesto solo se presente la dirigenza).',
      },
      {
        label: 'Equilibrio di bilancio esercizio precedente',
        key: 'pnrr.equilibrioEsercizioPrecedente',
        type: 'boolean',
        cellType: 'input_required',
        note: 'Verifica del rispetto del pareggio e dell\'equilibrio di bilancio (Sì/No).',
      },
      {
        label: 'Rispetto parametri debito commerciale e ritardi pagamenti',
        key: 'pnrr.parametriDebitoCommercialeEsercizioPrecedente',
        type: 'boolean',
        cellType: 'input_required',
        note: 'Verifica della regolarità nei pagamenti commerciali delle transazioni (Sì/No).',
      },
      {
        label: 'Modalità calcolo incidenza salario accessorio',
        key: 'pnrr.incidenzaSalarioAccessorioScelta',
        type: 'select',
        cellType: 'input_required',
        options: ['diretto', 'assistito'],
        note: 'Metodo: "diretto" per inserire direttamente la percentuale, "assistito" per inserire spesa e personale e farla calcolare.',
      },
      {
        label: 'Incidenza salario accessorio su spesa personale (percentuale)',
        key: 'pnrr.incidenzaSalarioAccessorioPercentuale',
        type: 'number',
        cellType: 'input_optional',
        note: 'Valore percentuale inserito direttamente (limite 8%).',
      },
      {
        label: 'Spesa salario accessorio per indicatori',
        key: 'pnrr.salarioAccessorioIndicatori',
        type: 'number',
        cellType: 'input_optional',
        note: 'Spesa per salario accessorio erogata (usata per il calcolo dell\'incidenza).',
      },
      {
        label: 'Spesa complessiva personale per indicatori',
        key: 'pnrr.spesaPersonaleIndicatori',
        type: 'number',
        cellType: 'input_optional',
        note: 'Spesa complessiva del personale (usata per il calcolo dell\'incidenza).',
      },
      {
        label: 'Rendiconto anno precedente approvato nei termini dall\'organo consiliare',
        key: 'pnrr.rendicontoApprovatoTermini',
        type: 'boolean',
        cellType: 'input_required',
        note: 'Verifica dell\'approvazione nei termini di legge del rendiconto consiliare (Sì/No).',
      },
    ],
  },
];
