export type Wizard2026EntityType =
  | 'REGIONE'
  | 'CITTA_METROPOLITANA'
  | 'PROVINCIA'
  | 'COMUNE'
  | 'UNIONE_COMUNI'
  | 'COMUNITA_MONTANA'
  | 'COMUNITA_ISOLANA_O_ARCIPELAGO'
  | 'CAMERA_COMMERCIO'
  | 'ENTE_REGIONALE'
  | 'ENTE_PARCO'
  | 'CONSORZIO'
  | 'ASP'
  | 'AZIENDA_SPECIALE'
  | 'ISTITUZIONE'
  | 'ALTRO_ENTE_STRUMENTALE'
  | 'ALTRO';

export type Dl25ApplicabilityStatus =
  | 'DIRECTLY_APPLICABLE'
  | 'TRANSFER_ONLY'
  | 'NOT_APPLICABLE'
  | 'NEEDS_MANUAL_REVIEW';
