const fs = require('fs');
const content = fs.readFileSync('src/types.ts', 'utf8');
const marker = '// --- Tipi Normativa ---';
const idx = content.indexOf(marker);
if (idx === -1) { console.error('Marker not found'); process.exit(1); }
const beforeNormativa = content.substring(0, idx);

const newSection = [
'// --- Tipi Normativa ---',
'',
"export type NormativaUnitaTipo = 'comma' | 'lettera' | 'sublettera' | 'punto' | 'appendice';",
'',
'export interface NormativaUnita {',
'  tipo: NormativaUnitaTipo;',
'  label: string;',
'  testo: string;',
'  figli?: NormativaUnita[];',
'}',
'',
'export interface RinvioInterno {',
'  label: string;',
'  targetId: string;',
'  posizione: number;',
'  fontePrevista: string;',
'  ambiguita: boolean;',
'}',
'',
'export interface NormativaArticle {',
'  id: string;',
'  label: string;',
'  titolo: string;',
'  titoloSezione: string;',
"  capo: string | null;",
'  fonte: string;',
'  codice?: string;',
'  testoIntegrale: string;',
'  strutturaNormativa: NormativaUnita[];',
'  rinviiInterni: RinvioInterno[];',
'  riferimentiEsterni: string[];',
'  pareriCollegati: string[];',
"  commi?: { numero: string; testo: string }[];",
'  rinviiEstratti?: string[];',
'}',
'',
"export interface NormativaBlocco {",
"  tipo: 'testo' | 'lista' | 'intestazione';",
"  chiaveStandard?: 'cosE' | 'quantoDura' | 'quando' | 'aChi' | 'chiDispone' | 'puoEssereNegato' | 'requisiti' | 'note' | 'pareriAran';",
'  contenuto: string | string[];',
'}',
'',
'export interface NormativaSchedaGuida {',
'  id: string;',
'  titolo: string;',
'  sezione: string;',
'  riferimentiNormativi: string[];',
'  blocchi: NormativaBlocco[];',
'  testoCompleto: string;',
'  pareriCorrelati: string[];',
'  articoliCollegati: string[];',
'  testoIntegrale?: string;',
'}',
'',
'export interface NormativaParereAran {',
'  id: string;',
'  dataPubblicazione: string;',
'  quesito: string;',
'  risposta: string;',
'  argomenti: string[];',
'  hashTagsArgomento: string[];',
'  riferimentiNormativiEstratti: string[];',
'  articoliCollegati: string[];',
'  schedeCollegate: string[];',
'  data?: string;',
'  domanda?: string;',
'  tags?: string[];',
'}',
'',
'export interface NormativaIndexEntry {',
'  id: string;',
"  type: 'articolo' | 'guida' | 'aran';",
'  title: string;',
'  subtitle?: string;',
'  content: string;',
'  meta?: {',
'    titoloSezione?: string;',
'    capo?: string;',
'    fonte?: string;',
'    sezione?: string;',
'    riferimentiNormativi?: string[];',
'    argomenti?: string[];',
'    hashTags?: string[];',
'  };',
'}',
'',
'export interface IndiceAnaliticoEntry {',
'  id: string;',
'  label: string;',
'  subLabel?: string;',
'  pageRefsOriginali: string;',
'  relatedArticleIds: string[];',
'  relatedSchedaIds: string[];',
'  relatedParereIds: string[];',
'}',
'',
'export interface NormativaExternalRef {',
'  id: string;',
'  pattern: string[];',
'  label: string;',
'  url: string;',
"  target: '_blank' | '_self';",
'}',
'',
'export type NormativaAnaliticoEntry = IndiceAnaliticoEntry;',
"export type NormativaComma = { numero: string; testo: string };",
'export type NormativaDettaglioBlocco = NormativaBlocco;',
''
].join('\n');

fs.writeFileSync('src/types.ts', beforeNormativa + newSection);
console.log('types.ts aggiornato. Lunghezza totale:', (beforeNormativa + newSection).length);
